<head>
  <link href="/compass/stylesheets/screen.css" media="screen, projection" rel="stylesheet" type="text/css" />
  <link href="/compass/stylesheets/print.css" media="print" rel="stylesheet" type="text/css" />
  <!--[if IE]>
      <link href="/compass/stylesheets/ie.css" media="screen, projection" rel="stylesheet" type="text/css" />
  <![endif]-->
  
  <!-- for freebase suggest -->
  <link type="text/css" rel="stylesheet" href="http://freebaselibs.com/static/suggest/1.0.3/suggest.min.css" />
</head>

