<ul>
  <li><a name="0" class="oa_selected">7 minutes ago</a></li>
  <li><a name="1">14 minutes ago</a></li>
  <li><a name="2">32 minutes ago</a></li>
  <li><a name="3">1 1/2 hours ago</a></li>
  <li><a name="4">2 hours ago</a></li>
  <li><a name="5">5 hours ago</a></li>
  <li><a name="6">6 hours 7 minutes ago</a></li>
  <li><a name="7">2 days ago</a></li>
  <li><a name="8">2 days ago</a></li>
  <li><a name="9">last week</a></li>
</ul>