<div class="item">
  <blockquote class="description">
    <span class="bqstart">&#8220;</span>Al Arabiyya reports a figure of $3.8 million stolen - as opposed to the BBC 's claim of $7 million, and also says that the money was "salaries of Iraqi police at the interior ministry"<span class="bqend">&#8221;</span>
  </blockquote>

  <ul class="attribution">
    <li class="timestamp">Added 7 minutes ago</span>
    <li class="posted_by">by <a href="index.php?page=profile&profileid=326" title="( ياسيرهك)">yaserhk</a> from <a class="source_title" href="http://www.jpost.com/servlet/Satellite?pagename=JPost/JPArticle/ShowFull&cid=1248277893143"> <a href="site-url">jpost.com</a></li>
  </ul>
  
  <ul class="editor">
    <li class="tagger"><label for="soft_input">Add Tags:</label><input id="soft_input" type="text"/></li>
    <li class="tags" id="msg">
      <span class="left">source:</span><span class="right">Jerusalem Post</span>
      <span class="left">org:</span><span class="right">BBC</span>
      <span class="left">org:</span><span class="right">Al Arabiyya</span>
      <span class="left">loc:</span><span class="right">Iraq</span>
    </li>
    
    <li class="link_title">This quote appeared on this page: <a href="#">Hamas Prime Minister Haniyeh loses 10,000 Facebook Friends | Jerusalem Post</a></span></li>
    <li class="pub_date">First appeared on the web: </li>
    
    <li class="related event">Related Meedan Discussions: <a href="index.php?page=events&post_id=279785">Facebook shuts down Hamas leader’s popular fan page</a></li>
    <li class="original_link"><a href="#">English Original at Jerusalem Post</a></li>
    <li class="translation_link"><a href="#"><a href="">Arabic Translation</a> of <a href="#">Jerusalem Post</a> article</a></li>
    <li class="translation"><a href="#">Help <a href="http://meedan.net">Translate</a> this Page</a></li>
    <li class="comment"><a href="index.php?page=events&post_id=279785#post-279819">0 Replies</a></li>
    <li class="links"><a href="#">5 Related Links</a></li>
  </ul> <!-- end uleditor -->
</div> 